
include: package:lints/recommended.yaml

linter:
  rules:
    - avoid_print
    - cancel_subscriptions
    - close_sinks
    - prefer_final_locals
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_single_quotes
