
name: debug_console_overlay
description: "A lightweight in-app debug overlay for Flutter showing logs in a floating console (disabled in release). MVP: draggable bubble, logs panel, search & filters, print/FlutterError capture helper."
version: 0.1.0
homepage: https://github.com/yourusername/debug_console_overlay
repository: https://github.com/yourusername/debug_console_overlay
issue_tracker: https://github.com/yourusername/debug_console_overlay/issues

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.18.0
  # Optional dependency for Dio HTTP client support
  dio: ^5.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.25.0
  lints: ^5.0.0

flutter:
  uses-material-design: true
